title:              RELIC
description:        "Research Library Companion"
author:             Ninjuku Studio
baseurl:            ""

# Collections
collections:
  posts:
    title: "Posts"
    output: true
  pages:
    title: "Pages"
    output: true

# Build settings
markdown: kramdown
## paginate: 5
## paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
##  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
